# Generated by Django 5.2.8 on 2025-12-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0006_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='vistas',
            field=models.IntegerField(default=0),
        ),
    ]
