# Generated by Django 5.2.8 on 2025-12-02 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0007_historia_vistas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='historia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historias.historia'),
        ),
        migrations.AlterField(
            model_name='historia',
            name='vistas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('lector', 'Lector'), ('autor', 'Autor'), ('moderador', 'Moderador')], default='lector', max_length=20),
        ),
        migrations.AlterField(
            model_name='rating',
            name='estrellas',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historias.historia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
